/*********************************************************************************************************************
 *  COPYRIGHT
 *  ------------------------------------------------------------------------------------------------------------------
 *  \verbatim
 *
 *                 TEXAS INSTRUMENTS INCORPORATED PROPRIETARY INFORMATION
 *
 *                 Property of Texas Instruments, Unauthorized reproduction and/or distribution
 *                 is strictly prohibited.  This product  is  protected  under  copyright  law
 *                 and  trade  secret law as an  unpublished work.
 *                 (C) Copyright 2025 Texas Instruments Inc.  All rights reserved.
 *
 *  \endverbatim
 *  ------------------------------------------------------------------------------------------------------------------
 *  FILE DESCRIPTION
 *  ------------------------------------------------------------------------------------------------------------------
 *  File:       Spi_Cfg.h
 *  Generator:  Elektrobit Tresos
 *
 *  Description:  This file contains generated configuration data for SPI MCAL driver
 *********************************************************************************************************************/

 /*****************************************************************************
   This file is generated by EB Tresos
   Do not modify this file, otherwise the software may behave in unexpected way.
 ******************************************************************************/

#ifndef SPI_CFG_H_
#define SPI_CFG_H_

/** \addtogroup SPI
 *  @{
 */
/*********************************************************************************************************************
 *
 * If building with a C++ compiler, make all of the definitions in this header
 * have a C binding.
 *
 *********************************************************************************************************************/

#ifdef __cplusplus
extern "C" {
#endif

/*********************************************************************************************************************
 * Header Files
 *********************************************************************************************************************/
/*
* Design:MCAL-25114
*/

#include "Spi_Example_Sync_AsyncTransfer.h"
#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*********************************************************************************************************************
 * Version Check (if required)
 *********************************************************************************************************************/

/*********************************************************************************************************************
 * Exported Preprocessor #define Constants
 *********************************************************************************************************************/

/** \brief Spi configuration Major Version */
#define SPI_CFG_MAJOR_VERSION           (3U)
/** \brief Spi configuration Minor Version */
#define SPI_CFG_MINOR_VERSION           (0U)
/** \brief Spi configuration Patch Version */
#define SPI_CFG_PATCH_VERSION           (0U)


/**
*  \brief SPI Build Variant.
*   Build variants.(i.e Pre Compile,Post Build or Link time)
*/
/** \brief  SPI build Pre-compile variant ON or OFF*/
#define SPI_PRE_COMPILE_VARIANT       (STD_OFF)
/** \brief  SPI build Post Build variant ON or OFF*/
#define SPI_VARIANT_POST_BUILD        (STD_ON)
/** \brief  SPI build Link Time variant ON or OFF*/
#define SPI_LINK_TIME_VARIANT         (STD_OFF)


/** \brief FIFO Tx Interrupt level */
#define SPI_FIFO_TX_INTERRUPT_LEVEL ((uint8)0x2U)

/** \brief FIFO Rx Interrupt level */
#define SPI_FIFO_RX_INTERRUPT_LEVEL ((uint8)0xBU)

/** \brief FIFO Tx FIFO Depth */
#define SPI_FIFO_TX_FIFO_DEPTH ((uint8)0x10U)

/** \brief FIFO Rx FIFO Depth */
#define SPI_FIFO_RX_FIFO_DEPTH ((uint8)0x10U)

/*
 * Design : MCAL-24875, MCAL-24876, MCAL-25161, MCAL-25107, MCAL-24899, MCAL-24889
 */
/** \brief Buffer mode - Internal or External or Both */
#define SPI_CHANNEL_BUFFERS          (SPI_IB_EB)

/** \brief Internal Buffer length in bytes - applicable only for SPI_IB */
/*
 * Design : MCAL-25162
 */
#define SPI_IB_MAX_LENGTH          ((uint8)(64U))

/** \brief Enable/disable SPI dev detect error */
/*
 * Design : MCAL-25108
 */
#define SPI_DEV_ERROR_DETECT        (STD_ON)

/**
 * \brief Scalability levels
 */
/** \brief Basic Synchronous functions */
#define SPI_LEVEL_0                  (0U)
/** \brief Basic Asynchronous functions */
#define SPI_LEVEL_1                  (1U)
/** \brief Synchronous and Asynchronous functions */
#define SPI_LEVEL_2                  (2U)

/** \brief Concurrent sync transmit support - by default this is off */
/*
 * Design : MCAL-25113
 */
#define SPI_SUPPORT_CONCURRENT_SYNC_TRANSMIT    (STD_ON)

/*
 * Design : MCAL-24858, MCAL-24859, MCAL-24914, MCAL-24915, MCAL-25111, MCAL-24889
 */
/** \brief Scalability level */
#define SPI_SCALABILITY            (SPI_LEVEL_2)

/** \brief Enable/disable SPI get version info API */
/*
 * Design : MCAL-25115
 */
#define SPI_VERSION_INFO_API        (STD_ON)

/** \brief Enable/disable SPI HW Status API */
/*
 * Design : MCAL-25109
 */
#define SPI_HW_STATUS_API           (STD_ON)

/** \brief Enable/disable SPI cancel API */
/*
 * Design : MCAL-25106
 */
#define SPI_CANCEL_API              (STD_OFF)

/*
 * All below macros are used for static memory allocation and can be changed to
 * match the use-case requirements.
 */
/** \brief Maximum channels across all jobs/sequence/hwunit */
/*
 * Design : MCAL-25149
 */
#define SPI_MAX_CHANNELS            ((uint16)(4U))

/** \brief Maximum jobs across all sequence/hwunit */
/*
 * Design : MCAL-25150
 */
#define SPI_MAX_JOBS                ((uint16)(3U))

/** \brief Maximum sequence across all hwunit */
/*
 * Design : MCAL-25151
 */
#define SPI_MAX_SEQ                 ((uint16)(2U))

/** \brief SPI timeout - used in SPI synchronous transmission.
 *  Specifies the maximum time for blocking function until a timeout is detected.
 * Units is clock cycles
 */

/*
 * Design: MCAL-28863
 */


#define SPI_CFG_TIMEOUT_CLOCK_CYCLES    ((McalLib_TickType)(100000U))

/** \brief Maximum channels allowed per job */
/*
 * Design : MCAL-25163, MCAL-25155
 */
#define SPI_MAX_CHANNELS_PER_JOB    ((uint8)2U)

/** \brief Maximum jobs allowed per sequence */
/*
 * Design : MCAL-25164
 */
#define SPI_MAX_JOBS_PER_SEQ       ((uint8)2U)

/**
 *  \brief Maximum HW unit - This should match the sum for the below units ISR
 *  which are ON.
 */
/*
 * Design : MCAL-25165, MCAL-25153
 */
#define SPI_MAX_HW_UNIT             ((uint8)2U)

/**
 *  \brief Maximum external device cfg
 */
/*
 * Design : MCAL-25166
 */
#define SPI_MAX_EXT_DEV             ((uint8)2U)


/*********************************************************************************************************************
 * Exported Preprocessor #define Macros
 *********************************************************************************************************************/

/*
 All below macros are used for enabling the ISR for a particular hardware.
 */

/** \brief Enable/disable SPI Instance ISR */
#define SPI_UNIT_SPIA_ACTIVE
/*
 * Design : MCAL-25154
 */
/** \brief Macro defining SPI Instance ISR type */
#define SPI_SPIA_ISR_CAT1_RTINT

/** \brief Enable/disable SPI Instance ISR */
#define SPI_UNIT_SPIB_ACTIVE
/*
 * Design : MCAL-25154
 */
/** \brief Macro defining SPI Instance ISR type */
#define SPI_SPIB_ISR_CAT2


/** \brief Symbolic Name Channel Id  - 0 SpiChannel_0 */
#define SpiConf_SpiChannel_SpiChannel_0  ((Spi_ChannelType)  0U)  /*~ASR~*/
/** \brief Symbolic Name Channel Id  - 1 SpiChannel_1 */
#define SpiConf_SpiChannel_SpiChannel_1  ((Spi_ChannelType)  1U)  /*~ASR~*/
/** \brief Symbolic Name Channel Id  - 2 SpiChannel_2 */
#define SpiConf_SpiChannel_SpiChannel_2  ((Spi_ChannelType)  2U)  /*~ASR~*/
/** \brief Symbolic Name Channel Id  - 3 SpiChannel_3 */
#define SpiConf_SpiChannel_SpiChannel_3  ((Spi_ChannelType)  3U)  /*~ASR~*/
/*
 * Design : MCAL-25138, MCAL-25140
 */
/** \brief Symbolic Name Job Id - 0 SpiJob_0 */
#define SpiConf_SpiJob_SpiJob_0    ((Spi_JobType) 0U)           /*~ASR~*/
/** \brief Symbolic Name Job Id - 1 SpiJob_1 */
#define SpiConf_SpiJob_SpiJob_1    ((Spi_JobType) 1U)           /*~ASR~*/
/** \brief Symbolic Name Job Id - 2 SpiJob_2 */
#define SpiConf_SpiJob_SpiJob_2    ((Spi_JobType) 2U)           /*~ASR~*/

/** \brief Symbolic Name Sequence Id - 0 SpiSequence_0 */
#define SpiConf_SpiSequence_SpiSequence_0 ((Spi_SequenceType) 0U)  /*~ASR~*/
/** \brief Symbolic Name Sequence Id - 1 SpiSequence_1 */
#define SpiConf_SpiSequence_SpiSequence_1 ((Spi_SequenceType) 1U)  /*~ASR~*/

/** \brief Symbolic Name HW Unit - SPI_UNIT_SPIA */
#define SpiConf_SpiExternalDevice_SpiExternalDevice_0_HwUnitId0 SPI_UNIT_SPIA /*~ASR~*/
/** \brief Symbolic Name HW Unit - SPI_UNIT_SPIB */
#define SpiConf_SpiExternalDevice_SpiExternalDevice_1_HwUnitId1 SPI_UNIT_SPIB /*~ASR~*/

/** \brief macro for invalid CS Identifier to which is greater than max channels supported */
#define SPI_PERIPHERAL_CS_IDENTIFIER      256U

/** \brief Symbolic Name Chip Select  - SPI_PERIPHERAL_CS_IDENTIFIER */
#define SpiConf_SpiExternalDevice_SpiExternalDevice_0_CS (SPI_PERIPHERAL_CS_IDENTIFIER) /*~ASR~*/
/** \brief Symbolic Name Chip Select  - SPI_PERIPHERAL_CS_IDENTIFIER */
#define SpiConf_SpiExternalDevice_SpiExternalDevice_1_CS (SPI_PERIPHERAL_CS_IDENTIFIER) /*~ASR~*/



/** \brief Macro to ON/OFF CS_VIA_GPIO using DIO module */
#define SPI_CS_VIA_GPIO       STD_OFF
/** \brief Symbolic Name for the SPI Dem no event */
#define DemConf_DemEventParameter_SPI_DEM_NO_EVENT (0xFFFFU)                /*~ASR~*/
/** \brief Symbolic Name for the SPI Dem no event */
/* Design: MCAL-24857 */
#define SPI_DEM_NO_EVENT DemConf_DemEventParameter_SPI_DEM_NO_EVENT 



/** \brief Mask for the configured Hw Instance */
#define SPI_CFG_ENABLED_HW_MASK             (0U \
                                                  | (1U << (uint8)SPI_UNIT_SPIA)\
                                                  | (1U << (uint8)SPI_UNIT_SPIB))
#ifndef SPI_E_HARDWARE_ERROR
/*
 * Design :  MCAL-24933, MCAL-25104,  MCAL-25103
 */
/** \brief SPI DEM hardware error ID */
#define SPI_E_HARDWARE_ERROR        (SPI_DEM_NO_EVENT)
#endif



/**
 *  \brief Total HW units - used for array allocation. This should be +1 of the
 *  max unit number
 */
#define SPI_HW_UNIT_CNT                 ((uint8)5U)

#endif /* DOXYGEN_SHOULD_SKIP_THIS */
/*********************************************************************************************************************
 * Exported Type Declarations
 *********************************************************************************************************************/

/** \brief Type of application data buffer elements */
/* 
 * Design :MCAL-24975, MCAL-24976  
 */
typedef uint8 Spi_DataBufferType;
/** \brief GPIO ID type */
typedef uint32 Spi_CsGpioType;
/** \brief type for the register pointer */
typedef uint32 Spi_RegisterPtrType;
/**
 *  \brief Type for defining the number of data elements of the type
 *  Spi_DataBufferType to send and / or receive by Channel
 */
/* Design : MCAL-24977 */
typedef uint16 Spi_NumberOfDataType;
/** \brief Specifies the identification (ID) for a Channel */
/* Design : MCAL-24978,MCAL-24979 */
typedef uint8 Spi_ChannelType;
/** \brief Specifies the identification (ID) for a Job */
/* Design : MCAL-24980,MCAL-24981 */
typedef uint16 Spi_JobType;
/** \brief Typedef for job end notification function pointer */
/* Design : MCAL-25094 */
typedef void (*Spi_JobEndNotifyType)( void ) ;
/** \brief Typedef for sequence end notification function pointer */
/* Design : MCAL-25097 */
typedef void (*Spi_SeqEndNotifyType)( void ) ;
/** \brief Specifies the identification (ID) for a sequence of jobs */
/* Design : MCAL-24982,MCAL-24983 */
typedef uint8 Spi_SequenceType;
/**
 *  \brief Specifies the identification (ID) for a SPI Hardware micro
 *   controller  peripheral (unit)
 */
/* Design : MCAL-24984,MCAL-24985 */
typedef uint8 Spi_HWUnitType;

/**
 *  \brief This type defines Channel Select Interface with in SPI(SPI instance)
 */
 typedef enum
{
    /** \brief SPIA instance */
    SPI_UNIT_SPIA,
    /** \brief SPIB instance */
    SPI_UNIT_SPIB,
    /** \brief SPIC instance */
    SPI_UNIT_SPIC,
    /** \brief SPID instance */
    SPI_UNIT_SPID,
    /** \brief SPIE instance */
    SPI_UNIT_SPIE,
} Spi_HwInstance;

/*
 * Design : MCAL-24955   
 */
/**
 *  \brief This type defines a range of specific Driver status for SPI
 *  Handler/Driver
 */
typedef enum
{
    /** \brief The SPI Handler/Driver is not initialized or not usable */
    SPI_UNINIT = 0U,
    /** \brief The SPI Handler/Driver is not currently transmitting any Job */
    SPI_IDLE = 1U,
    /** \brief The SPI Handler/Driver is performing a SPI Job (transmit) */
    SPI_BUSY = 2U
} Spi_StatusType;

/**
 *  \brief This type defines a range of specific Jobs status for SPI
 *  Handler/Driver
 */
/* 
 * Design :MCAL-24995,MCAL-24964,MCAL-24965,MCAL-24966
 */
typedef enum
{
    /** \brief The last transmission of the Job has been finished successfully */
    SPI_JOB_OK = 0U,
    /** \brief The SPI Handler/Driver is performing a SPI Job.
     * The meaning of this status is equal to SPI_BUSY */
    SPI_JOB_PENDING = 1U,
    /** \brief The last transmission of the Job has failed */
    SPI_JOB_FAILED = 2U,
    /** \brief An asynchronous transmit Job has been accepted, while
     * actual transmission for this Job has not started yet */
    SPI_JOB_QUEUED = 3U
} Spi_JobResultType;

/**
 *  \brief This type defines a range of specific Sequences status for
 *  SPI Handler/Driver
 */
/*
 * Design :MCAL-24973,MCAL-24974,MCAL-24971,MCAL-24969,MCAL-24970,MCAL-24968 
 */
typedef enum
{
    /** \brief The last transmission of the Sequence has been finished
	 * successfully */
    SPI_SEQ_OK = 0U,
    /** \brief The SPI Handler/Driver is performing a SPI Sequence.
	 * The meaning of this status is equal to SPI_BUSY */
    SPI_SEQ_PENDING = 1U,
    /** \brief The last transmission of the Sequence has failed */
    SPI_SEQ_FAILED = 2U,
    /** \brief The last transmission of the Sequence has been canceled by
	 * user */
    SPI_SEQ_CANCELLED = 3U
} Spi_SeqResultType;

/**
 *  \brief This type defines a range of specific HW unit status for
 *  SPI Handler/Driver
 */
typedef enum
{
    /** \brief HW unit result is ok */
    SPI_HW_UNIT_OK = 0U,
    /** \brief HW unit result is pending */
    SPI_HW_UNIT_PENDING = 1U,
    /** \brief HW unit result is failed */
    SPI_HW_UNIT_FAILED = 2U
} Spi_HwUnitResultType;

/**
 *  \brief Specifies the asynchronous mechanism mode for SPI busses
 *   handled asynchronously in LEVEL 2
 */
/*
 * Design : MCAL-24986,MCAL-24986,MCAL-24988,MCAL-24989,MCAL-24990,MCAL-24987 
 */
typedef enum
{
    /** \brief The asynchronous mechanism is ensured by polling, so
	* interrupts related to SPI busses handled asynchronously
	* are disabled */
    SPI_POLLING_MODE = 0U,
    /** \brief The asynchronous mechanism is ensured by
     * interrupt, so interrupts related to SPI busses
     * handled asynchronously are enabled */
    SPI_INTERRUPT_MODE = 1U
} Spi_AsyncModeType;

/**
 *  \brief Word transfer order - MSB first or LSB first
 */
typedef enum
{
    /** \brief MSB is transferred first. Only this is supported */
    SPI_MSB = 0U,
    /** \brief LSB is transferred first. This is not supported */
    SPI_LSB = 1U

} Spi_TransferType;


/**
 *  \brief Spi Cs Selection - Chip select handling
 */

/*
 * Design : MCAL-25171
 */
typedef enum
{
    /** \brief chip select is handled via general purpose IO by Spi driver */
    CS_VIA_GPIO,
    /** \brief chip select is handled automatically by Peripheral HW engine */
    CS_VIA_PERIPHERAL_ENGINE

} Spi_CsSelection;


/**
 *  \brief SPI Clock Mode - sets the clock polarity and phase.
 *   Note: These values are a direct register mapping.
 *   So don't change value.
 */
/*
 * Design : MCAL-25170
 */
typedef enum
{
    /** \brief SPI Clock Phase = 0  Polarity = 0 */
    SPI_CLK_MODE_0 = 0x00U,
    /** \brief SPI Clock Phase = 1 Polarity = 0  */
    SPI_CLK_MODE_1 = 0x01U,
    /** \brief SPI Clock Phase = 0 Polarity = 1  */
    SPI_CLK_MODE_2 = 0x02U,
    /** \brief SPI Clock Phase = 1 Polarity = 1  */
    SPI_CLK_MODE_3 = 0x03U,
} Spi_ClkMode;

/**
 *  \brief SPI Job Priority.
 */
/*
 * Design : MCAL-25168, MCAL-24896
 */
typedef enum
{
    /** \brief Job priority 0 - low */
    SPI_JOB_PRIORITY_0,
    /** \brief Job priority 1*/
    SPI_JOB_PRIORITY_1,
    /** \brief Job priority 2 */
    SPI_JOB_PRIORITY_2,
    /** \brief Job priority 3 - High */
    SPI_JOB_PRIORITY_3
} Spi_JobPriorityType;

/* Design : MCAL-25167 */
/**
 *  \brief Spi_DataDelayType defines the number of SPI serial clock cycles delay between each word in FIFO mode
 */
typedef uint8 Spi_DataDelayType;

/**
 *  \brief SPI Channel configuration structure.
 */
/*
 *Design : MCAL-25172
 */
typedef struct
{
    /** \brief Channel ID */
	Spi_ChannelType       channelId;
    /** \brief Buffer Type IB/EB */
    uint8                 channelBufType;
    /** \brief Width of clock frame in bits.
     * In case of SPI, valid values are from 1 to 16 bits. */
    uint8                 dataWidth;
     /** \brief Default transmit value when TX buffer is NULL */
    uint16                defaultTxData;
    /** \brief Max data length for external or internal buffer in SPI words.
     * In case of internal buffers, this represents the number of
	 *  words to  copy from application buffer to internal buffer
	 * in case of Spi_WriteIB() API or from internal buffer to
	 * application buffer in case of Spi_ReadIB().
     * The value of this should be less than or equal to the SPI
     * configuration SPI_IB_MAX_LENGTH as this macro is is used for
 	 * buffer allocation.
     */
    Spi_NumberOfDataType  maxBufLength;
    /** \brief Start with MSB or LSB.
     *   Only MSB is supported.  */
    Spi_TransferType      transferType;

} Spi_ChannelConfigType;

/*
 * Design : MCAL-24863 , MCAL-25176
 */
/**
 * \brief SPI external device specific configuration structure .
 */
typedef struct
{
    /** \brief External device ID */
    uint8                externalDeviceId;
    /** \brief Chip select functionality on/off */
    uint16               csEnable;

    /** \brief Chip select pin polarity high or low */
    uint8        csPolarity;

    /** \brief Clock divider. This is used to derive the required baudrate
	 *  from the SPI functional clock.
     *  Maximum allowed value of divider is 127(7 bit register field)
     * For clkDivider = 3 to 127: SPI Baud Rate = SYSCLK / (clkDivider + 1)
     * For clkDivider = 0, 1, or 2: SPI Baud Rate = SYSCLK / 4 */
    uint16               clkDivider;
    /** \brief Mode 0 = {0=CPOL,0=CPHA}; Mode 1={0,1}; Mode 2={1,0}
	 * Mode 3={1,1} */
    Spi_ClkMode          clkMode;

    /** \brief delay between each word in FIFO mode */
    Spi_DataDelayType    wordDelay;

} Spi_ExternalDeviceConfigType;

/**
 *  \brief SPI Job configuration structure.
 */
/*
 * Design : MCAL-24895, MCAL-24895, MCAL-25173, MCAL-25095,MCAL-25096,MCAL-25094,MCAL-25091, 
 * Design :MCAL-25090, MCAL-25087
 */
typedef struct
{
    /** \brief Job ID */
	Spi_JobType            jobId;
    /** \brief Job priority */
    Spi_JobPriorityType    jobPriority;
    /** \brief Job end notification callback fxn pointer */
    Spi_JobEndNotifyType   Spi_JobEndNotification;
    /** \brief index into SpiConfig.extDevCfg[] indicating the devCfg associated
     *   with the job */
	uint8                externalDeviceCfgId;
    /** \brief Chip select pin to use */
	Spi_CsSelection        csSelect;
    /** \brief if csSelect is GPIO then which GPIO to select as CS */
    Spi_CsGpioType         csGpioId;
    /** \brief HWUnit associated with this job */
    Spi_HWUnitType         hwUnitId;
    /** \brief Number of channels for this job.
     *  Should not be more than SPI_MAX_CHANNELS_PER_JOB */
    uint32                 channelPerJob;
    /** \brief Channel index list */
    Spi_ChannelType        channelList[SPI_MAX_CHANNELS_PER_JOB];

    
} Spi_JobConfigType;

/**
 *  \brief SPI Sequence configuration structure.
 */
/*
 *Design : MCAL-24905, MCAL-24906, MCAL-24908, MCAL-24910, MCAL-24911,MCAL-24907
 *Design : MCAL-24909, MCAL-24913, MCAL-25174, 
 */
/* Design : MCAL-25090,MCAL-25091,MCAL-25088,MCAL-25089, MCAL-24899 */
typedef struct
{
    /** \brief Sequence ID */
	Spi_SequenceType     seqId;
    /** \brief Sequence interruptible or not (TRUE/FALSE) */
    uint8                seqInterruptible;
    /** \brief Sequence end notification callback fxn pointer */
    Spi_SeqEndNotifyType Spi_SequenceEndNotification;
    /** \brief Number of jobs for this sequence.
     *   Should not be more than SPI_MAX_JOBS_PER_SEQ */
    uint32               jobPerSeq;
    /** \brief Job index list */
    Spi_JobType          jobList[SPI_MAX_JOBS_PER_SEQ];
} Spi_SeqConfigType;

/**
 *  \brief SPI Hardware unit configuration structure.
 */
/*
 *Design : MCAL-25175
 */
typedef struct
{
    /** \brief SPI HW unit to use */
    Spi_HWUnitType hwUnitId;
    /** \brief SPI HW unit base address */
    uint32         HwUnitBaseAddr;
    /** \brief Enables High speed mode for SPI instance */
    boolean        hsModeEnable;
    /** \brief SPI FIFO Enhancements Enable */
    boolean        fifoModeEnable;
    /** \brief SPI Loop Back node Enable */
    boolean        loopBackEnable;
    /** \brief SPI Rx PIPE Vector number for this hardware unit */
    uint32         RxPIPEVectorID;
} Spi_HwUnitConfigType;

/**
 *  \brief SPI config structure
 */

/*
 * Design : MCAL-24949, MCAL-24950, MCAL-24951, MCAL-24952, MCAL-24953, MCAL-24954,MCAL-24950
 */
typedef struct Spi_ConfigType_s
{
    /** \brief Maximum number of channels.
     *   Should not be more than SPI_MAX_CHANNELS */
    uint8                        maxChannels;
    /** \brief Maximum number of jobs
     *   Should not be more than SPI_MAX_JOBS */
    uint8                        maxJobs;
    /** \brief Maximum number of sequences
     *   Should not be more than SPI_MAX_SEQ */
    uint8                        maxSeq;
    /** \brief Maximum number of HW unit
     *   Should not be more than SPI_MAX_HW_UNIT */
    uint8                        maxHwUnit;
    /** \brief Maximum number of external device configurations
     *   Should not be more than SPI_MAX_EXT_DEV */
    uint8                        maxExtDevCfg;
    /** \brief Channel configurations */
    Spi_ChannelConfigType        channelCfg[SPI_MAX_CHANNELS];
    /** \brief Job configurations */
    Spi_JobConfigType            jobCfg[SPI_MAX_JOBS];
    /** \brief Sequence configurations */
    Spi_SeqConfigType            seqCfg[SPI_MAX_SEQ];
    /** \brief HW Unit configurations */
    Spi_HwUnitConfigType         hwUnitCfg[SPI_MAX_HW_UNIT];
    /** \brief External HW device config */
    Spi_ExternalDeviceConfigType extDevCfg[SPI_MAX_EXT_DEV];
    
} Spi_ConfigType;

/*********************************************************************************************************************
 * Exported Object Declarations
 *********************************************************************************************************************/

extern const uint32 Spi_HwUnitBaseAddr[SPI_HW_UNIT_CNT];


/** \brief SPI Configuration struct declaration */
extern CONST(struct Spi_ConfigType_s, SPI_CONFIG_DATA) Spi_Config;

/*********************************************************************************************************************
 *  Exported Function Prototypes
 *********************************************************************************************************************/
 
/*********************************************************************************************************************
 *  Exported Inline Function Definitions and Function-Like Macros
 *********************************************************************************************************************/

#ifdef __cplusplus
}
#endif
/**
* @}
*/
#endif  /* #ifndef SPI_CFG_H_ */
/*********************************************************************************************************************
 *  End of File: Spi_Cfg.h
 *********************************************************************************************************************/
