[!SKIPFILE "node:value(as:modconf('Spi')[as:path(node:dtos(.))='/TI_F29H85x/Spi']/IMPLEMENTATION_CONFIG_VARIANT) != 'VariantPostBuild'"!]
/*********************************************************************************************************************
 *  COPYRIGHT
 *  ------------------------------------------------------------------------------------------------------------------
 *  \verbatim
 *
 *                 TEXAS INSTRUMENTS INCORPORATED PROPRIETARY INFORMATION
 *
 *                 Property of Texas Instruments, Unauthorized reproduction and/or distribution
 *                 is strictly prohibited.  This product  is  protected  under  copyright  law
 *                 and  trade  secret law as an  unpublished work.
 *                 (C) Copyright [!"substring-before($date,'-')"!] Texas Instruments Inc.  All rights reserved.
 *
 *  \endverbatim
 *  ------------------------------------------------------------------------------------------------------------------
 *  FILE DESCRIPTION
 *  ------------------------------------------------------------------------------------------------------------------
 *  File:       Spi_PBcfg.c
 *  Generator:  Elektrobit Tresos
 *
 *  Description:  This file contains generated configuration data for Post-Build Variant
 *********************************************************************************************************************/

/*****************************************************************************
    This file is generated by EB Tresos
    Do not modify this file, otherwise the software may behave in unexpected way
 ******************************************************************************/

/*********************************************************************************************************************
 * Header Files
 *********************************************************************************************************************/
#include "Spi.h"
#include "Spi_Priv.h"

/*********************************************************************************************************************
 * Version Check (if required)
 * AUTOSAR version information check has to match definition in header file.
 *********************************************************************************************************************/
#if ((SPI_SW_MAJOR_VERSION != ([!"substring-before($moduleSoftwareVer,'.')"!]U)) || (SPI_SW_MINOR_VERSION != ([!"substring-before(substring-after($moduleSoftwareVer,'.'),'.')"!]U)))
  #error "Version numbers of Spi_PBcfg.c and Spi.h are inconsistent!"
#endif

#if ((SPI_CFG_MAJOR_VERSION != ([!"substring-before($moduleSoftwareVer,'.')"!]U)) || (SPI_CFG_MINOR_VERSION != ([!"substring-before(substring-after($moduleSoftwareVer,'.'),'.')"!]U)))
  #error "Version numbers of Spi_PBcfg.c and Spi_Cfg.h are inconsistent!"
#endif
/*********************************************************************************************************************
 * Local Preprocessor #define Constants
 *********************************************************************************************************************/

/*********************************************************************************************************************
 * Local Preprocessor #define Macros
 *********************************************************************************************************************/

/*********************************************************************************************************************
 * Local Type Declarations
 *********************************************************************************************************************/

/*********************************************************************************************************************
 * Exported Function Prototypes
 *********************************************************************************************************************/

/*********************************************************************************************************************
 * Object Definitions
 *********************************************************************************************************************/
#define  SPI_START_SEC_CONFIG_DATA
#include "Spi_MemMap.h"
/* generation of runtime configuration       */

#ifdef __cplusplus
extern "C" {
#endif

[!AUTOSPACING!]



[!SELECT "as:modconf('Spi')[as:path(node:dtos(.))='/TI_F29H85x/Spi']"!]
/*
 * Design : MCAL-24860, MCAL-24861, MCAL-24866, MCAL-24867, MCAL-24868, MCAL-24869, 
 * Design : MCAL-24870, MCAL-25160, MCAL-25145, MCAL-25121, MCAL-25122, MCAL-25123,
 * Design : MCAL-25124, MCAL-25125, MCAL-25126, MCAL-25127, MCAL-25128, MCAL-25141,
 * Design : MCAL-25142, MCAL-25144, MCAL-25146, MCAL-25159, MCAL-25132, MCAL-25134,
 * Design : MCAL-25135, MCAL-25136, MCAL-25137, MCAL-25129, MCAL-25130, MCAL-25131,
 * Design : MCAL-25116, MCAL-25117, MCAL-25118, MCAL-25119, MCAL-25120, MCAL-25160,
 * Design : MCAL-25105, MCAL-24883  
 */
[!LOOP "SpiDriver"!][!//
CONST(struct Spi_ConfigType_s, SPI_CONFIG_DATA) Spi_ConfigObj =
{
[!WS "4"!].maxChannels = [!IF "node:exists("SpiMaxChannel")"!][!"SpiMaxChannel"!]U[!ELSE!][!"num:i(count(SpiChannel/*))"!]U[!ENDIF!],
[!WS "4"!].maxJobs = [!IF "node:exists("SpiMaxJob")"!][!"SpiMaxJob"!]U[!ELSE!][!"num:i(count(SpiJob/*))"!]U[!ENDIF!],
[!WS "4"!].maxSeq  = [!IF "node:exists("SpiMaxSequence")"!][!"SpiMaxSequence"!]U[!ELSE!][!"num:i(count(SpiSequence/*))"!]U[!ENDIF!],
[!WS "4"!].maxHwUnit = [!"num:i(count(SpiHwUnitConfig/*))"!]U,
[!WS "4"!].maxExtDevCfg = [!"num:i(count(SpiExternalDevice/*))"!]U,
[!WS "4"!].channelCfg =
[!WS "4"!]{
[!WS "4"!][!LOOP "SpiChannel/*"!]
[!WS "4"!][!WS "4"!][[!"@index"!]] =
[!WS "4"!][!WS "4"!][!WS "4"!]{
[!WS "4"!][!WS "4"!][!WS "4"!][!WS "4"!].channelId = SpiConf_SpiChannel_[!"@name"!],
[!WS "4"!][!WS "4"!][!WS "4"!][!WS "4"!].channelBufType = [!"concat('SPI_',SpiChannelType)"!],
[!IF "as:modconf('Spi')[as:path(node:dtos(.))='/TI_F29H85x/Spi']/SpiGeneral/SpiChannelBuffersAllowed = '1'"!][!//
[!IF "SpiChannelType = 'IB'"!][!//
[!ERROR "SpiChannelBuffersAllowed parameter should be selected as EB or IB/EB or SpiChannelType should be EB"!][!//
[!ENDIF!][!//
[!ELSEIF "as:modconf('Spi')[as:path(node:dtos(.))='/TI_F29H85x/Spi']/SpiGeneral/SpiChannelBuffersAllowed = '0'"!][!//
[!IF "SpiChannelType = 'EB'"!][!//
[!ERROR "SpiChannelBuffersAllowed parameter should be selected as IB or IB/EB or SpiChannelType should be IB"!][!//
[!ENDIF!][!//
[!ENDIF!][!//
[!WS "4"!][!WS "4"!][!WS "4"!][!WS "4"!].dataWidth = [!"SpiDataWidth"!]U,
[!IF "SpiDataWidth < '9'"!][!//
[!VAR "BufWidth" = "1"!][!//
[!ELSEIF "SpiDataWidth < '17'"!][!//
[!VAR "BufWidth" = "2"!][!//
[!ELSE!][!//
[!ERROR "SpiDataWidth cannot be more than 16"!][!//
[!ENDIF!][!//
[!VAR "SpiChannelIBBufferMaxLength" = "as:modconf('Spi')[as:path(node:dtos(.))='/TI_F29H85x/Spi']/SpiGeneral/SpiChannelInternalBufferMaxLength"!]
[!WS "4"!][!WS "4"!][!WS "4"!][!WS "4"!].defaultTxData = [!IF "node:exists(SpiDefaultData) and not(node:empty(SpiDefaultData))"!][!"node:value(SpiDefaultData)"!]U[!ELSE!]0U[!ENDIF!],
[!WS "4"!][!WS "4"!][!WS "4"!][!WS "4"!].maxBufLength = [!IF "SpiChannelType = 'EB'"!][!"SpiEbMaxLength"!]U[!ELSE!][!"SpiIbNBuffers"!]U[!ENDIF!],
[!IF "as:modconf('Spi')[as:path(node:dtos(.))='/TI_F29H85x/Spi']/SpiGeneral/SpiChannelBuffersAllowed != '1'"!]
[!IF "SpiChannelType = 'IB'"!]
[!IF "SpiIbNBuffers * num:i($BufWidth) > num:i($SpiChannelIBBufferMaxLength) "!][!//
[!ERROR "Value of maxBufLength should be less than or equal to the SPI configuration SPI_IB_MAX_LENGTH in case of Internal Buffer(Refer MCAL-24874)!!"!]
[!ENDIF!]
[!ENDIF!]
[!ENDIF!]
[!WS "4"!][!WS "4"!][!WS "4"!][!WS "4"!].transferType = [!"concat('SPI_',SpiTransferStart)"!],
[!WS "4"!][!WS "4"!][!WS "4"!]},
[!WS "4"!][!ENDLOOP!]
[!WS "4"!]},
[!WS "4"!].jobCfg =
[!WS "4"!]{
[!WS "4"!][!LOOP "SpiJob/*"!]
[!WS "4"!][!WS "4"!][[!"@index"!]] =
[!WS "4"!][!WS "4"!][!WS "4"!]{
[!WS "4"!][!WS "4"!][!WS "4"!][!WS "4"!].jobId = SpiConf_SpiJob_[!"@name"!],
[!WS "4"!][!WS "4"!][!WS "4"!][!WS "4"!].jobPriority = [!"concat('SPI_JOB_PRIORITY_',SpiJobPriority)"!],
[!WS "4"!][!WS "4"!][!WS "4"!][!WS "4"!].Spi_JobEndNotification = [!IF "not(node:empty(SpiJobEndNotification))"!][!"SpiJobEndNotification"!][!ELSE!]NULL_PTR[!ENDIF!],
[!WS "4"!][!WS "4"!][!WS "4"!][!WS "4"!].externalDeviceCfgId = (uint8)[!"node:value(node:ref(node:current()/SpiDeviceAssignment)/SpiExternalDeviceId)"!],
[!WS "4"!][!WS "4"!][!WS "4"!][!WS "4"!].csSelect = [!IF "node:exists(node:ref(node:current()/SpiDeviceAssignment)/SpiCsSelection)"!][!"node:value(node:ref(node:current()/SpiDeviceAssignment)/SpiCsSelection)"!][!ELSE!]CS_VIA_PERIPHERAL_ENGINE[!ENDIF!],
[!WS "4"!][!WS "4"!][!WS "4"!][!WS "4"!].csGpioId = SpiConf_SpiExternalDevice_[!"node:name(node:ref(node:current()/SpiDeviceAssignment))"!]_CS,
[!WS "4"!][!WS "4"!][!WS "4"!][!WS "4"!].hwUnitId = (Spi_HwInstance) [!"node:value(node:ref(node:current()/SpiDeviceAssignment)/SpiHwUnit)"!],
[!WS "4"!][!WS "4"!][!WS "4"!][!WS "4"!].channelPerJob = [!"num:i(count(SpiChannelList/*))"!]U,
[!WS "4"!][!WS "4"!][!WS "4"!][!WS "4"!].channelList =
[!WS "4"!][!WS "4"!][!WS "4"!][!WS "4"!]{
                                        [!LOOP "SpiChannelList/*"!]
[!WS "4"!][!WS "4"!][!WS "4"!][!WS "4"!][!WS "4"!][[!"SpiChannelIndex"!]] = [!"node:value(node:ref(node:current()/SpiChannelAssignment)/SpiChannelId)"!]U,
                                        [!ENDLOOP!]
[!WS "4"!][!WS "4"!][!WS "4"!][!WS "4"!]},
[!WS "4"!][!WS "4"!][!WS "4"!]},
[!WS "4"!][!ENDLOOP!]
[!WS "4"!]},
[!WS "4"!].seqCfg =
[!WS "4"!]{
[!WS "4"!][!LOOP "SpiSequence/*"!]
[!WS "4"!][!WS "4"!][[!"@index"!]] =
[!WS "4"!][!WS "4"!][!WS "4"!]{
[!WS "4"!][!WS "4"!][!WS "4"!][!WS "4"!].seqId = SpiConf_SpiSequence_[!"@name"!],
[!WS "4"!][!WS "4"!][!WS "4"!][!WS "4"!].seqInterruptible = (uint8) [!"text:toupper(SpiInterruptibleSequence)"!],
[!WS "4"!][!WS "4"!][!WS "4"!][!WS "4"!].Spi_SequenceEndNotification = [!IF "not(node:empty(SpiSeqEndNotification))"!][!"SpiSeqEndNotification"!][!ELSE!]NULL_PTR[!ENDIF!],
[!WS "4"!][!WS "4"!][!WS "4"!][!WS "4"!].jobPerSeq = [!"num:i(count(SpiJobAssignment/*))"!]U,
[!WS "4"!][!WS "4"!][!WS "4"!][!WS "4"!].jobList =
[!WS "4"!][!WS "4"!][!WS "4"!][!WS "4"!]{
                                        [!LOOP "SpiJobAssignment/*"!]
[!WS "4"!][!WS "4"!][!WS "4"!][!WS "4"!][!WS "4"!][[!"@index"!]] =[!"node:value(node:ref(node:current())/SpiJobId)"!]U,
                                        [!ENDLOOP!]
[!WS "4"!][!WS "4"!][!WS "4"!][!WS "4"!]},
[!WS "4"!][!WS "4"!][!WS "4"!]},
[!WS "4"!][!ENDLOOP!]
[!WS "4"!]},
[!WS "4"!].hwUnitCfg =
[!WS "4"!]{
[!WS "4"!][!LOOP "SpiHwUnitConfig/*"!]
[!WS "4"!][!WS "4"!][[!"@index"!]] =
[!WS "4"!][!WS "4"!][!WS "4"!]{
[!WS "4"!][!WS "4"!][!WS "4"!][!WS "4"!].hwUnitId = (Spi_HwInstance) [!"SpiHwUnitType"!],
[!WS "4"!][!WS "4"!][!WS "4"!][!WS "4"!].hsModeEnable = (boolean) [!IF "SpiHighSpeedMode = 'true'"!]TRUE[!ELSE!]FALSE[!ENDIF!],
[!WS "4"!][!WS "4"!][!WS "4"!][!WS "4"!].fifoModeEnable = (boolean) [!IF "SpiFifoModeEnable = 'true'"!]TRUE[!ELSE!]FALSE[!ENDIF!],
[!WS "4"!][!WS "4"!][!WS "4"!][!WS "4"!].loopBackEnable = (boolean) [!IF "SpiLoopBackMode = 'true'"!]TRUE[!ELSE!]FALSE[!ENDIF!],
[!WS "4"!][!WS "4"!][!WS "4"!][!WS "4"!].RxPIPEVectorID = [!IF "SpiHwUnitType = 'SPI_UNIT_SPIA'"!]INT_SPIA_RX[!ELSEIF "SpiHwUnitType = 'SPI_UNIT_SPIB'"!]INT_SPIB_RX[!//
[!ELSEIF "SpiHwUnitType = 'SPI_UNIT_SPIC'"!]INT_SPIC_RX[!//
[!ELSEIF "SpiHwUnitType = 'SPI_UNIT_SPID'"!]INT_SPID_RX[!//
[!ELSEIF "SpiHwUnitType = 'SPI_UNIT_SPIE'"!]INT_SPIE_RX[!//
[!ELSE!][!//
[!ERROR "Invalid SpiHwUnitType configured"!][!//
[!ENDIF!],
[!WS "4"!][!WS "4"!][!WS "4"!]},
[!WS "4"!][!ENDLOOP!]
[!WS "4"!]},
[!WS "4"!].extDevCfg =
[!WS "4"!]{
[!WS "4"!][!LOOP "SpiExternalDevice/*"!]
[!WS "4"!][!WS "4"!][[!"@index"!]] =
[!WS "4"!][!WS "4"!][!WS "4"!]{
[!WS "4"!][!WS "4"!][!WS "4"!][!WS "4"!].externalDeviceId = (uint8)[!"SpiExternalDeviceId"!]U,
[!WS "4"!][!WS "4"!][!WS "4"!][!WS "4"!].csEnable = (uint16) [!IF "SpiEnableCs = 'true'"!]TRUE[!ELSE!]FALSE[!ENDIF!],
[!WS "4"!][!WS "4"!][!WS "4"!][!WS "4"!].csPolarity = [!"concat('STD_',SpiCsPolarity)"!],
[!WS "4"!][!WS "4"!][!WS "4"!][!WS "4"!].clkDivider = (uint32) [!"SpiclkDivider"!]U,
                                       [!IF "SpiShiftClockIdleLevel = 'LOW'"!]
                                       [!IF "SpiDataShiftEdge = 'TRAILING'"!]
[!WS "4"!][!WS "4"!][!WS "4"!][!WS "4"!].clkMode = (Spi_ClkMode) SPI_CLK_MODE_0,
                                       [!ELSE!]
[!WS "4"!][!WS "4"!][!WS "4"!][!WS "4"!].clkMode = (Spi_ClkMode) SPI_CLK_MODE_1,
                                       [!ENDIF!]
                                       [!ELSE!]
                                       [!IF "SpiDataShiftEdge = 'TRAILING'"!]
[!WS "4"!][!WS "4"!][!WS "4"!][!WS "4"!].clkMode = (Spi_ClkMode) SPI_CLK_MODE_2,
                                       [!ELSE!]
[!WS "4"!][!WS "4"!][!WS "4"!][!WS "4"!].clkMode = (Spi_ClkMode) SPI_CLK_MODE_3,
                                       [!ENDIF!]
                                       [!ENDIF!]
[!WS "4"!][!WS "4"!][!WS "4"!][!WS "4"!].wordDelay = (Spi_DataDelayType) [!"SpiDataWordDelay"!]U,
[!WS "4"!][!WS "4"!][!WS "4"!]},
[!WS "4"!][!ENDLOOP!]
[!WS "4"!]},
};
[!ENDLOOP!][!//
[!ENDSELECT!]



/**
 *  \brief This type defines a range of HW SPI Hardware microcontroller
 *         peripheral allocated to this Job
 */
const uint32 Spi_HwUnitBaseAddr[SPI_HW_UNIT_CNT] =
{
   0x70158000 ,      	    /* SPIA */
   0x70159000 ,      	    /* SPIB */
   0x7015A000 ,      	    /* SPIC */
   0x7015B000 ,      	    /* SPID */
   0x7015C000 ,     	    /* SPIE */
};

#ifdef __cplusplus
}
#endif

#define  SPI_STOP_SEC_CONFIG_DATA
#include "Spi_MemMap.h"

/*********************************************************************************************************************
 * Exported Object Definitions
 *********************************************************************************************************************/

/*********************************************************************************************************************
 * Local Object Definitions
 *********************************************************************************************************************/

/*********************************************************************************************************************
 * Local Function Prototypes
 *********************************************************************************************************************/

/*********************************************************************************************************************
 * Local Inline Function Definitions and Function-Like Macros
 *********************************************************************************************************************/

/*********************************************************************************************************************
 * External Functions Definition
 *********************************************************************************************************************/

/*********************************************************************************************************************
 * Local Functions Definition
 *********************************************************************************************************************/

/*********************************************************************************************************************
 * End of File: Spi_PBcfg.c
 *********************************************************************************************************************/