/*********************************************************************************************************************
 *  COPYRIGHT
 *  ------------------------------------------------------------------------------------------------------------------
 *  \verbatim
 *
 *                 TEXAS INSTRUMENTS INCORPORATED PROPRIETARY INFORMATION
 *
 *                 Property of Texas Instruments, Unauthorized reproduction and/or distribution
 *                 is strictly prohibited.  This product  is  protected  under  copyright  law
 *                 and  trade  secret law as an  unpublished work.
 *                 (C) Copyright 2025 Texas Instruments Inc.  All rights reserved.
 *
 *  \endverbatim
 *  ------------------------------------------------------------------------------------------------------------------
 *  FILE DESCRIPTION
 *  ------------------------------------------------------------------------------------------------------------------
 *  File:       Spi_Lcfg.c
 *  Generator:  Elektrobit Tresos
 *
 *  Description:  This file contains generated configuration data for Link-Time Variant
 *********************************************************************************************************************/

/*****************************************************************************
    This file is generated by EB Tresos
    Do not modify this file, otherwise the software may behave in unexpected way
 ******************************************************************************/

/*********************************************************************************************************************
 * Header Files
 *********************************************************************************************************************/
#include "Spi.h"
#include "Spi_Priv.h"

/*********************************************************************************************************************
 * Version Check (if required)
 * AUTOSAR version information check has to match definition in header file.
 *********************************************************************************************************************/
#if ((SPI_SW_MAJOR_VERSION != (3U)) || (SPI_SW_MINOR_VERSION != (0U)))
  #error "Version numbers of Spi_Lcfg.c and Spi.h are inconsistent!"
#endif

#if ((SPI_CFG_MAJOR_VERSION != (3U)) || (SPI_CFG_MINOR_VERSION != (0U)))
  #error "Version numbers of Spi_Lcfg.c and Spi_Cfg.h are inconsistent!"
#endif
/*********************************************************************************************************************
 * Local Preprocessor #define Constants
 *********************************************************************************************************************/

/*********************************************************************************************************************
 * Local Preprocessor #define Macros
 *********************************************************************************************************************/

/*********************************************************************************************************************
 * Local Type Declarations
 *********************************************************************************************************************/

/*********************************************************************************************************************
 * Exported Function Prototypes
 *********************************************************************************************************************/

/*********************************************************************************************************************
 * Object Definitions
 *********************************************************************************************************************/
#define  SPI_START_SEC_CONFIG_DATA
#include "Spi_MemMap.h"
/* generation of runtime configuration       */

#ifdef __cplusplus
extern "C" {
#endif




/*
 * Design : MCAL-24860, MCAL-24861, MCAL-24866, MCAL-24867, MCAL-24868, MCAL-24869, 
 * Design : MCAL-24870, MCAL-25160, MCAL-25145, MCAL-25121, MCAL-25122, MCAL-25123,
 * Design : MCAL-25124, MCAL-25125, MCAL-25126, MCAL-25127, MCAL-25128, MCAL-25141,
 * Design : MCAL-25142, MCAL-25144, MCAL-25146, MCAL-25159, MCAL-25132, MCAL-25134,
 * Design : MCAL-25135, MCAL-25136, MCAL-25137, MCAL-25129, MCAL-25130, MCAL-25131,
 * Design : MCAL-25116, MCAL-25117, MCAL-25118, MCAL-25119, MCAL-25120, MCAL-25160,
 * Design : MCAL-25105, MCAL-24883
 */
CONST(struct Spi_ConfigType_s, SPI_CONFIG_DATA) Spi_Config =
{
    .maxChannels = 3U,
    .maxJobs = 4U,
    .maxSeq  = 2U,
    .maxHwUnit = 2U,
    .maxExtDevCfg = 2U,
    .channelCfg =
    {
            [0] =
            {
                .channelId = SpiConf_SpiChannel_SpiChannel_0,
                .channelBufType = SPI_IB,
                .dataWidth = 8U,
                .defaultTxData = 65530U,
                .maxBufLength = 30U,
                .transferType = SPI_MSB,
            },
            [1] =
            {
                .channelId = SpiConf_SpiChannel_SpiChannel_1,
                .channelBufType = SPI_IB,
                .dataWidth = 6U,
                .defaultTxData = 11U,
                .maxBufLength = 11U,
                .transferType = SPI_MSB,
            },
            [2] =
            {
                .channelId = SpiConf_SpiChannel_SpiChannel_2,
                .channelBufType = SPI_EB,
                .dataWidth = 8U,
                .defaultTxData = 0U,
                .maxBufLength = 10U,
                .transferType = SPI_MSB,
            },
        },
    .jobCfg =
    {
            [0] =
            {
                .jobId = SpiConf_SpiJob_SpiJob_0,
                .jobPriority = SPI_JOB_PRIORITY_1,
                .Spi_JobEndNotification = job0_endNotification,
                .externalDeviceCfgId = (uint8)0,
                .csSelect = CS_VIA_PERIPHERAL_ENGINE,
                .csGpioId = SpiConf_SpiExternalDevice_SpiExternalDevice_0_CS,
                .hwUnitId = (Spi_HwInstance) SPI_UNIT_SPIA,
                .channelPerJob = 2U,
                .channelList =
                {
                    [0] = 0U,
                    [1] = 1U,
                },
            },
            [1] =
            {
                .jobId = SpiConf_SpiJob_SpiJob_1,
                .jobPriority = SPI_JOB_PRIORITY_2,
                .Spi_JobEndNotification = NULL_PTR,
                .externalDeviceCfgId = (uint8)0,
                .csSelect = CS_VIA_PERIPHERAL_ENGINE,
                .csGpioId = SpiConf_SpiExternalDevice_SpiExternalDevice_0_CS,
                .hwUnitId = (Spi_HwInstance) SPI_UNIT_SPIA,
                .channelPerJob = 1U,
                .channelList =
                {
                    [0] = 2U,
                },
            },
            [2] =
            {
                .jobId = SpiConf_SpiJob_SpiJob_2,
                .jobPriority = SPI_JOB_PRIORITY_2,
                .Spi_JobEndNotification = NULL_PTR,
                .externalDeviceCfgId = (uint8)1,
                .csSelect = CS_VIA_PERIPHERAL_ENGINE,
                .csGpioId = SpiConf_SpiExternalDevice_SpiExternalDevice_1_CS,
                .hwUnitId = (Spi_HwInstance) SPI_UNIT_SPIB,
                .channelPerJob = 1U,
                .channelList =
                {
                    [0] = 0U,
                },
            },
            [3] =
            {
                .jobId = SpiConf_SpiJob_SpiJob_3,
                .jobPriority = SPI_JOB_PRIORITY_3,
                .Spi_JobEndNotification = NULL_PTR,
                .externalDeviceCfgId = (uint8)1,
                .csSelect = CS_VIA_PERIPHERAL_ENGINE,
                .csGpioId = SpiConf_SpiExternalDevice_SpiExternalDevice_1_CS,
                .hwUnitId = (Spi_HwInstance) SPI_UNIT_SPIB,
                .channelPerJob = 1U,
                .channelList =
                {
                    [0] = 2U,
                },
            },
        },
    .seqCfg =
    {
            [0] =
            {
                .seqId = SpiConf_SpiSequence_SpiSequence_0,
                .seqInterruptible = (uint8) FALSE,
                .Spi_SequenceEndNotification = sequence0_endNotification,
                .jobPerSeq = 2U,
                .jobList =
                {
                    [0] =0U,
                    [1] =3U,
                },
            },
            [1] =
            {
                .seqId = SpiConf_SpiSequence_SpiSequence_1,
                .seqInterruptible = (uint8) FALSE,
                .Spi_SequenceEndNotification = NULL_PTR,
                .jobPerSeq = 1U,
                .jobList =
                {
                    [0] =2U,
                },
            },
        },
    .hwUnitCfg =
    {
            [0] =
            {
                .hwUnitId = (Spi_HwInstance) SPI_UNIT_SPIA,
                .HwUnitBaseAddr = (uint32) SPIA_BASE_FRAME(0U),
                .hsModeEnable = (boolean) FALSE,
                .fifoModeEnable = (boolean) TRUE,
                .loopBackEnable = (boolean) TRUE,
                .RxPIPEVectorID = INT_SPIA_RX,
            },
            [1] =
            {
                .hwUnitId = (Spi_HwInstance) SPI_UNIT_SPIB,
                .HwUnitBaseAddr = (uint32) SPIB_BASE_FRAME(0U),
                .hsModeEnable = (boolean) FALSE,
                .fifoModeEnable = (boolean) TRUE,
                .loopBackEnable = (boolean) TRUE,
                .RxPIPEVectorID = INT_SPIB_RX,
            },
        },
    .extDevCfg =
    {
            [0] =
            {
                .externalDeviceId = (uint8)0U,
                .csEnable = (uint16) FALSE,
                .csPolarity = STD_LOW,
                .clkDivider = (uint32) 21U,
                .clkMode = (Spi_ClkMode) SPI_CLK_MODE_0,
                .wordDelay = (Spi_DataDelayType) 0U,
            },
            [1] =
            {
                .externalDeviceId = (uint8)1U,
                .csEnable = (uint16) FALSE,
                .csPolarity = STD_LOW,
                .clkDivider = (uint32) 66U,
                .clkMode = (Spi_ClkMode) SPI_CLK_MODE_1,
                .wordDelay = (Spi_DataDelayType) 0U,
            },
        },
};
#ifdef __cplusplus
}
#endif

#define  SPI_STOP_SEC_CONFIG_DATA
#include "Spi_MemMap.h"

/*********************************************************************************************************************
 * Exported Object Definitions
 *********************************************************************************************************************/

/*********************************************************************************************************************
 * Local Object Definitions
 *********************************************************************************************************************/

/*********************************************************************************************************************
 * Local Function Prototypes
 *********************************************************************************************************************/

/*********************************************************************************************************************
 * Local Inline Function Definitions and Function-Like Macros
 *********************************************************************************************************************/

/*********************************************************************************************************************
 * External Functions Definition
 *********************************************************************************************************************/

/*********************************************************************************************************************
 * Local Functions Definition
 *********************************************************************************************************************/

/*********************************************************************************************************************
 * End of File: Spi_Lcfg.c
 *********************************************************************************************************************/
