/*********************************************************************************************************************
 *  COPYRIGHT
 *  ------------------------------------------------------------------------------------------------------------------
 *  \verbatim
 *
 *   TEXAS INSTRUMENTS TEXT FILE LICENSE
 *
 *   Copyright (c) 2025 Texas Instruments Incorporated
 *
 *   All rights reserved not granted herein.
 *
 *   Limited License.
 *
 *   Texas Instruments Incorporated grants a world-wide, royalty-free, non-exclusive
 *   license under copyrights and patents it now or hereafter owns or controls to
 *   make, have made, use, import, offer to sell and sell ("Utilize") this software
 *   subject to the terms herein. With respect to the foregoing patent license,
 *   such license is granted solely to the extent that any such patent is necessary
 *   to Utilize the software alone. The patent license shall not apply to any
 *   combinations which include this software, other than combinations with devices
 *   manufactured by or for TI ("TI Devices"). No hardware patent is licensed hereunder.
 *
 *   Redistributions must preserve existing copyright notices and reproduce this license
 *   (including the above copyright notice and the disclaimer and (if applicable) source
 *   code license limitations below) in the documentation and/or other materials provided
 *   with the distribution.
 *
 *   Redistribution and use in binary form, without modification, are permitted provided
 *   that the following conditions are met:
 *
 *   * No reverse engineering, decompilation, or disassembly of this software is
 *     permitted with respect to any software provided in binary form.
 *   * Any redistribution and use are licensed by TI for use only with TI Devices.
 *   * Nothing shall obligate TI to provide you with source code for the software
 *     licensed and provided to you in object code.
 *
 *   If software source code is provided to you, modification and redistribution of the
 *   source code are permitted provided that the following conditions are met:
 *
 *   * Any redistribution and use of the source code, including any resulting derivative
 *     works, are licensed by TI for use only with TI Devices.
 *   * Any redistribution and use of any object code compiled from the source code
 *     and any resulting derivative works, are licensed by TI for use only with TI Devices.
 *
 *   Neither the name of Texas Instruments Incorporated nor the names of its suppliers
 *   may be used to endorse or promote products derived from this software without
 *   specific prior written permission.
 *
 *   DISCLAIMER.
 *
 *   THIS SOFTWARE IS PROVIDED BY TI AND TI'S LICENSORS "AS IS" AND ANY EXPRESS OR IMPLIED
 *   WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 *   AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL TI AND TI'S
 *   LICENSORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 *   CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 *   GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 *   CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 *   EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 *  \endverbatim
 *  ------------------------------------------------------------------------------------------------------------------
 *  FILE DESCRIPTION
 *  ------------------------------------------------------------------------------------------------------------------
 *  File:       Spi_PBcfg.c
 *  Generator:  Elektrobit Tresos
 *
 *  Description:  This file contains generated configuration data for Post-Build Variant
 *********************************************************************************************************************/

/*****************************************************************************
    This file is generated by EB Tresos
    Do not modify this file, otherwise the software may behave in unexpected way
 ******************************************************************************/

/*********************************************************************************************************************
 * Header Files
 *********************************************************************************************************************/
#include "Spi.h"
#include "Spi_Priv.h"

/*********************************************************************************************************************
 * Version Check (if required)
 * AUTOSAR version information check has to match definition in header file.
 *********************************************************************************************************************/
#if ((SPI_SW_MAJOR_VERSION != (3U)) || (SPI_SW_MINOR_VERSION != (1U)))
  #error "Version numbers of Spi_PBcfg.c and Spi.h are inconsistent!"
#endif

#if ((SPI_CFG_MAJOR_VERSION != (3U)) || (SPI_CFG_MINOR_VERSION != (1U)))
  #error "Version numbers of Spi_PBcfg.c and Spi_Cfg.h are inconsistent!"
#endif
/*********************************************************************************************************************
 * Local Preprocessor #define Constants
 *********************************************************************************************************************/

/*********************************************************************************************************************
 * Local Preprocessor #define Macros
 *********************************************************************************************************************/

/*********************************************************************************************************************
 * Local Type Declarations
 *********************************************************************************************************************/

/*********************************************************************************************************************
 * Exported Function Prototypes
 *********************************************************************************************************************/

/*********************************************************************************************************************
 * Object Definitions
 *********************************************************************************************************************/
#define  SPI_START_SEC_CONFIG_DATA
#include "Spi_MemMap.h"
/* generation of runtime configuration       */

#ifdef __cplusplus
extern "C" {
#endif




/*
 * Design : MCAL-24860, MCAL-24861, MCAL-24866, MCAL-24867, MCAL-24868, MCAL-24869, 
 * Design : MCAL-24870, MCAL-25160, MCAL-25145, MCAL-25121, MCAL-25122, MCAL-25123,
 * Design : MCAL-25124, MCAL-25125, MCAL-25126, MCAL-25127, MCAL-25128, MCAL-25141,
 * Design : MCAL-25142, MCAL-25144, MCAL-25146, MCAL-25159, MCAL-25132, MCAL-25134,
 * Design : MCAL-25135, MCAL-25136, MCAL-25137, MCAL-25129, MCAL-25130, MCAL-25131,
 * Design : MCAL-25116, MCAL-25117, MCAL-25118, MCAL-25119, MCAL-25120, MCAL-25160,
 * Design : MCAL-25105, MCAL-24883  
 */
CONST(struct Spi_ConfigType_s, SPI_CONFIG_DATA) Spi_Config =
{
    .maxChannels = 4U,
    .maxJobs = 3U,
    .maxSeq  = 2U,
    .maxHwUnit = 2U,
    .maxExtDevCfg = 2U,
    .channelCfg =
    {
            [0] =
            {
                .channelId = SpiConf_SpiChannel_SpiChannel_0,
                .channelBufType = SPI_IB,
                .dataWidth = 8U,
                .defaultTxData = 65530U,
                .maxBufLength = 30U,
                .transferType = SPI_MSB,
            },
            [1] =
            {
                .channelId = SpiConf_SpiChannel_SpiChannel_1,
                .channelBufType = SPI_IB,
                .dataWidth = 6U,
                .defaultTxData = 11U,
                .maxBufLength = 11U,
                .transferType = SPI_MSB,
            },
            [2] =
            {
                .channelId = SpiConf_SpiChannel_SpiChannel_2,
                .channelBufType = SPI_EB,
                .dataWidth = 8U,
                .defaultTxData = 0U,
                .maxBufLength = 10U,
                .transferType = SPI_MSB,
            },
            [3] =
            {
                .channelId = SpiConf_SpiChannel_SpiChannel_3,
                .channelBufType = SPI_IB,
                .dataWidth = 10U,
                .defaultTxData = 0U,
                .maxBufLength = 10U,
                .transferType = SPI_MSB,
            },
        },
    .jobCfg =
    {
            [0] =
            {
                .jobId = SpiConf_SpiJob_SpiJob_0,
                .jobPriority = SPI_JOB_PRIORITY_1,
                .Spi_JobEndNotification = job0_endNotification,
                .externalDeviceCfgId = (uint8)0,
                .csSelect = CS_VIA_PERIPHERAL_ENGINE,
                .csGpioId = SpiConf_SpiExternalDevice_SpiExternalDevice_0_CS,
                .hwUnitId = (Spi_HWUnitType) SPI_UNIT_SPIA,
                .channelPerJob = 2U,
                .channelList =
                {
                    [0] = 0U,
                    [1] = 1U,
                },
            },
            [1] =
            {
                .jobId = SpiConf_SpiJob_SpiJob_1,
                .jobPriority = SPI_JOB_PRIORITY_2,
                .Spi_JobEndNotification = NULL_PTR,
                .externalDeviceCfgId = (uint8)0,
                .csSelect = CS_VIA_PERIPHERAL_ENGINE,
                .csGpioId = SpiConf_SpiExternalDevice_SpiExternalDevice_0_CS,
                .hwUnitId = (Spi_HWUnitType) SPI_UNIT_SPIA,
                .channelPerJob = 1U,
                .channelList =
                {
                    [0] = 2U,
                },
            },
            [2] =
            {
                .jobId = SpiConf_SpiJob_SpiJob_2,
                .jobPriority = SPI_JOB_PRIORITY_1,
                .Spi_JobEndNotification = NULL_PTR,
                .externalDeviceCfgId = (uint8)1,
                .csSelect = CS_VIA_PERIPHERAL_ENGINE,
                .csGpioId = SpiConf_SpiExternalDevice_SpiExternalDevice_1_CS,
                .hwUnitId = (Spi_HWUnitType) SPI_UNIT_SPIB,
                .channelPerJob = 1U,
                .channelList =
                {
                    [0] = 3U,
                },
            },
        },
    .seqCfg =
    {
            [0] =
            {
                .seqId = SpiConf_SpiSequence_SpiSequence_0,
                .seqInterruptible = (uint8) FALSE,
                .Spi_SequenceEndNotification = sequence0_endNotification,
                .jobPerSeq = 2U,
                .jobList =
                {
                    [0] =0U,
                    [1] =1U,
                },
            },
            [1] =
            {
                .seqId = SpiConf_SpiSequence_SpiSequence_1,
                .seqInterruptible = (uint8) FALSE,
                .Spi_SequenceEndNotification = NULL_PTR,
                .jobPerSeq = 1U,
                .jobList =
                {
                    [0] =2U,
                },
            },
        },
    .hwUnitCfg =
    {
            [0] =
            {
                .hwUnitId = (Spi_HWUnitType) SPI_UNIT_SPIA,
                .HwUnitBaseAddr = (uint32) SPIA_BASE_FRAME(0U),
                .hsModeEnable = (boolean) FALSE,
                .fifoModeEnable = (boolean) TRUE,
                .loopBackEnable = (boolean) TRUE,
                .RxPIPEVectorID = INT_SPIA_RX,
            },
            [1] =
            {
                .hwUnitId = (Spi_HWUnitType) SPI_UNIT_SPIB,
                .HwUnitBaseAddr = (uint32) SPIB_BASE_FRAME(0U),
                .hsModeEnable = (boolean) FALSE,
                .fifoModeEnable = (boolean) TRUE,
                .loopBackEnable = (boolean) FALSE,
                .RxPIPEVectorID = INT_SPIB_RX,
            },
        },
    .extDevCfg =
    {
            [0] =
            {
                .externalDeviceId = (uint8)0U,
                .csEnable = (uint16) FALSE,
                .csPolarity = STD_LOW,
                .clkDivider = (uint16) 21U,
                .clkMode = (Spi_ClkMode) SPI_CLK_MODE_0,
                .wordDelay = (Spi_DataDelayType) 0U,
            },
            [1] =
            {
                .externalDeviceId = (uint8)1U,
                .csEnable = (uint16) FALSE,
                .csPolarity = STD_LOW,
                .clkDivider = (uint16) 99U,
                .clkMode = (Spi_ClkMode) SPI_CLK_MODE_3,
                .wordDelay = (Spi_DataDelayType) 0U,
            },
        },
};
#ifdef __cplusplus
}
#endif

#define  SPI_STOP_SEC_CONFIG_DATA
#include "Spi_MemMap.h"

/*********************************************************************************************************************
 * Exported Object Definitions
 *********************************************************************************************************************/

/*********************************************************************************************************************
 * Local Object Definitions
 *********************************************************************************************************************/

/*********************************************************************************************************************
 * Local Function Prototypes
 *********************************************************************************************************************/

/*********************************************************************************************************************
 * Local Inline Function Definitions and Function-Like Macros
 *********************************************************************************************************************/

/*********************************************************************************************************************
 * External Functions Definition
 *********************************************************************************************************************/

/*********************************************************************************************************************
 * Local Functions Definition
 *********************************************************************************************************************/

/*********************************************************************************************************************
 * End of File: Spi_PBcfg.c
 *********************************************************************************************************************/
